
PATHDIR = ..\..\..
PATHINC = $(PATHDIR)\include
PATHLIB = $(PATHDIR)\lib\windows\dynamic

CC    = cl
CFLAGS = -I. -I.. -I$(PATHINC) -O2

all: 
	$(CC) $(CFLAGS) -nologo -o main main.c ..\SimpleLCP_Path.obj $(PATHLIB)\path46.lib

