
PATHDIR = ..\..
PATHINC = $(PATHDIR)\include
PATHLIB = $(PATHDIR)\lib\windows\static

CC    = mex
CFLAGS = -I. -I$(PATHINC) -O

all: 
	$(CC) $(CFLAGS) lcppath.c Matlab_Error.c Matlab_Memory.c $(PATHLIB)\path46.lib
	$(CC) $(CFLAGS) mcppath.c Matlab_Error.c Matlab_Memory.c $(PATHLIB)\path46.lib

