
PATHDIR = ..\..\..
PATHINC = $(PATHDIR)\include
PATHLIB = $(PATHDIR)\lib\windows\dynamic

F77   = f77
FFLAGS = -optimize:4 -math_library:fast

all: 
	$(F77) $(FFLAGS) -nologo -exe:linmcp linmcp.f ..\Standalone_Path.obj ..\StandaloneF_Output.obj ..\fout.obj $(PATHLIB)\path46.lib

