
PATHDIR = ../../..
PATHINC = $(PATHDIR)/include
PATHLIB = $(PATHDIR)/lib/linux/dynamic

CC    = gcc
CFLAGS = -I. -I.. -I$(PATHINC) -O3

all: 
	$(CC) $(CFLAGS) -o obstacle obstacle.c ../Standalone_Path.o -L$(PATHLIB) -lpath46 -lm

