
PATHDIR = ..\..
PATHINC = $(PATHDIR)\include
PATHLIB = $(PATHDIR)\lib\windows

CC    = cl
CFLAGS = -I. -I$(PATHINC) -DFNAME_UCASE_NODECOR -DF_CALLCONV=__stdcall -O2

F77   = f77
FFLAGS = -optimize:4 -math_library:fast

all: 
	$(CC) $(CFLAGS) -c -nologo Standalone_Path.c StandaloneF_Output.c
	$(F77) $(FFLAGE) -c -nologo fout.f

