
PATHDIR = ../..
PATHINC = $(PATHDIR)/include
PATHLIB = $(PATHDIR)/lib/linux

CC    = gcc
CFLAGS = -I. -I$(PATHINC) -DFNAME_LCASE_DECOR -O3

F77   = f77
FFLAGS = -O3

all: 
	$(CC) $(CFLAGS) -c Standalone_Path.c StandaloneF_Output.c
	$(F77) $(FFLAGS) -c fout.f

